[project]
name = "myproject"
version = "0.1.0"
description = "My first Python project"
authors = [
    { name="Your Name", email="you@example.com" }
]
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
